apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-namespace.yaml
- employee-deployment.yaml
- mongodb-configmap.yaml
- mongodb-secret.yaml
- mongodb-deployment.yaml

namespace: iso
images:

- name: employee-image
  newName: harbor.tanzu.be/library/iso-employee-service
  newTag: b2.20211006.175505